export { BaseService } from './BaseService';
export { forgotPassword, logout, getCurrentLoginUser, handleNavigateRole, login } from './auth'
export { changePassword, changeStatusUser, changeUserRole, createUser, deleteUser, getUserDetail, getUsers, register, updateUser } from './user'
export { getCategories, createCategory, deleteCategory, getCategoryDetail, updateCategory } from './category'
export { getContests, createConstest, deleteContest, updateContest } from './contest'
export { createCriteria, deleteCriteria, getCriteriaDetail, getCriterias, updateCriteria } from './criteria'
export { createBlog, deleteBlog, getBlog, getBlogs, handleGetBlogDetail, updateBlog } from './blog'
export { getVariety, getKois } from './koiFish'
export { getDashboard } from './dashboard'
export { evaluate } from './evaluation'