export { PATHS } from './paths'
export { API_PATHS } from './apiPaths'
export { ROLES, privateRole, rolesArr } from './roles'
export { getRoleColor, getRoleLabel } from './getRoleType'
export { avatarUrlRules, commentRules, contentRules, descriptionRules, emailRules, nameRules, passwordRules, phoneNumberRules, ratingRules, rejectRules, roleRules, titleRules, videoRules } from './formRules'
export { HttpStatus } from './httpStatus'
export { avatarReplace } from './others'
export { policies, sidebarPolicies, terms } from './terms'
export { companyLinks, legalLinks, solutionLinks, supportLinks } from './footer'